### ISSUE TITLE
AssertionError: applications must write bytes

### ISSUE THREAD

**Issue by russorat** [openbufo/influxdb-odata-server#1]
Awesome project! I'm seeing this with every request to the app. might be harmless.

```
➜  influxdb-odata-server git:(master) ✗ python startServer.py
Advertising service at http://localhost:8080/data
Starting HTTP server on: interface: 0.0.0.0, port: 8080...
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
Generating OData metadata xml file from InfluxDB metadata
127.0.0.1 - - [16/Apr/2020 11:00:19] "GET /configure/createmetadata/telegraf HTTP/1.1" 200 -
127.0.0.1 - - [16/Apr/2020 11:00:20] "GET /favicon.ico HTTP/1.1" 404 -
Error on request:
Traceback (most recent call last):
  File "/Users/rsavage/Library/Python/3.7/lib/python/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/Users/rsavage/Library/Python/3.7/lib/python/site-packages/werkzeug/serving.py", line 295, in execute
    write(data)
  File "/Users/rsavage/Library/Python/3.7/lib/python/site-packages/werkzeug/serving.py", line 275, in write
    assert isinstance(data, bytes), "applications must write bytes"
AssertionError: applications must write bytes
```

**Comment by openbufo** [comment]
Updated create-metadata logic with [https://github.com/openbufo/influxdb-odata-server/commit/698c87427282ceee5f0b7441d0a9af7d80cbf92f](commit). This should resolve the issue.
