### ISSUE TITLE
errors in metadata.xml

### ISSUE THREAD

**Issue by russorat** [openbufo/influxdb-odata-server#2]
I have a pretty large telegraf bucket with a lot of measurements. I was able to generate the metadata file, but when i start the server again, there are parsing errors.

this is the first one:
```
Traceback (most recent call last):
  File "startServer.py", line 169, in <module>
    doc = load_metadata(c)
  File "startServer.py", line 141, in load_metadata
    doc.read_from_stream(f)
  File "/usr/local/lib/python3.7/site-packages/pyslet/xml/structures.py", line 829, in read_from_stream
    self.read_from_entity(e)
  File "/usr/local/lib/python3.7/site-packages/pyslet/xml/structures.py", line 842, in read_from_entity
    parser.parse_document(self)
  File "/usr/local/lib/python3.7/site-packages/pyslet/xml/parser.py", line 1167, in parse_document
    self.parse_element()
  File "/usr/local/lib/python3.7/site-packages/pyslet/xml/parser.py", line 2206, in parse_element
    while self.parse_content():
  File "/usr/local/lib/python3.7/site-packages/pyslet/xml/parser.py", line 2660, in parse_content
    if not self.parse_element():
  File "/usr/local/lib/python3.7/site-packages/pyslet/xml/parser.py", line 2206, in parse_element
    while self.parse_content():
  File "/usr/local/lib/python3.7/site-packages/pyslet/xml/parser.py", line 2660, in parse_content
    if not self.parse_element():
  File "/usr/local/lib/python3.7/site-packages/pyslet/xml/parser.py", line 2206, in parse_element
    while self.parse_content():
  File "/usr/local/lib/python3.7/site-packages/pyslet/xml/parser.py", line 2660, in parse_content
    if not self.parse_element():
  File "/usr/local/lib/python3.7/site-packages/pyslet/xml/parser.py", line 2248, in parse_element
    self.element.content_changed()
  File "/usr/local/lib/python3.7/site-packages/pyslet/odata2/csdl.py", line 4097, in content_changed
    super(EntityType, self).content_changed()
  File "/usr/local/lib/python3.7/site-packages/pyslet/odata2/csdl.py", line 4050, in content_changed
    self.declare(p)
  File "/usr/local/lib/python3.7/site-packages/pyslet/odata2/csdl.py", line 519, in declare
    (value.name, key, self.name))
pyslet.odata2.csdl.IncompatibleNames: Can't declare com.docker.compose.project.config_files; com.docker.compose.project already declared in scope telegraf__docker_container_blkio
```

but fixing that, i see the following errors:
`pyslet.xml.parser.XMLWellFormedError: Line 290.0: Element Type Mismatch: found </EntityType>, expected <Schema/>`
`pyslet.odata2.csdl.IncompatibleNames: Can't declare com.docker.compose.project.config_files; com.docker.compose.project already declared in scope telegraf__docker_container_cpu`
`pyslet.odata2.csdl.IncompatibleNames: Can't declare com.docker.compose.project.config_files; com.docker.compose.project already declared in scope telegraf__docker_container_mem`
`pyslet.odata2.csdl.DuplicateName: ip_dscp already declared in scope telegraf__sflow`
`pyslet.odata2.csdl.DuplicateName: ip_ecn already declared in scope telegraf__sflow`
`pyslet.odata2.csdl.IncompatibleNames: Can't declare 0.001; 0 already declared in scope telegraf__tele_prom_metrics`
`pyslet.odata2.csdl.DuplicateName: tsunami already declared in scope telegraf__usgs`

Here's the metadata.xml file that was generated:
[metadata.xml.zip](https://github.com/openbufo/influxdb-odata-server/files/4488997/metadata.xml.zip)

**Comment by russorat** [comment]
i finally hacked all the errors out of the xml, but then tablaeu wouldn't connect.

**Comment by openbufo** [comment]
In telegraf.usgs measurement, 'tsumani' field has been declared twice. Metadata cannot have duplicate field and tags for same measurement. Also, both fields and tags are considered to be keys and appear in Odata schema as fields.
Regarding the issue with connecting Tableau, can you share the query/URI you have tried?
